### ISSUE TITLE
update scRNAseq workflow

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#53]
After last conversation on slack, I think the **scRNAseq** workflow is not in sync with the newer changes.. Maybe time to update it?

**Comment by steffenheyne** [comment]
Which changes you mean?

**Comment by vivekbhr** [comment]
Any updates present in current develop, like for example the trimming option were different between scRNAaseq and other workflows

**Comment by steffenheyne** [comment]
the slight differing trimming option was intentionally, as poly-A trimming is "easier" with cutadapt, therefore scRNA-seq supports only cutadapt right now....but I can change this for consistency

**Comment by vivekbhr** [comment]
@steffenheyne feel free to close this if you think it's done

**Comment by dpryan79** [comment]
Isn't `cutadapt` the default trimmer in the other workflows already? I wouldn't oppose getting rid of Trim Galore all together, since cutadapt is vastly faster.

**Comment by steffenheyne** [comment]
currently we just use always "AGATCGGAAGAGC"

**Comment by dpryan79** [comment]
We could make that configurable I suppose. I actually want to add a `--detect` option to cutadapt (I looked into making Trim Galore multithreading...but that'd be absurdly complicated). I think Trim Galore does an OK job for the most part with adapter detection, but of course if you know what the adapter is then that'll always be the most reliable. The WGBS pipeline has two different adapter sequences built in, so one can instead trim with Nextera adapters if needed. Maybe that's the way to go, since we don't currently support sRNA-seq.

**Comment by vivekbhr** [comment]
Yah if cutadapt rule can be adopted for multiple adaptor types, I would also vote to get rid of trim-galore

**Comment by steffenheyne** [comment]
see now here
https://github.com/maxplanck-ie/snakepipes/issues/151
