### ISSUE TITLE
ATAC-seq pipeline peak caller

### ISSUE THREAD

**Issue by tamerbio** [maxplanck-ie/snakepipes#553]
Hi everyone,
could anyone please add  `HMMRATAC` and `Genrich` as an option for ATAC peak calling?
Thanks
TA

**Comment by dpryan79** [comment]
FYI, I'm told that HMMRATAC is extremely slow, though perhaps that's just an older version.

**Comment by dpryan79** [comment]
I have these added locally. I can't say I'm impressed with HMMRATAC, but maybe our test data happens to be a worst-case scenario for it.

**Comment by tamerbio** [comment]
thanks much .. how to update snakePipes without the need to reinstall everything again?

**Comment by dpryan79** [comment]
You'll probably want to wait until we tag a new release (and certainly until I merge this into the develop branch today or tomorrow). The nice thing about `snakePipes createEnvs` is that it will skip environments that are already there.

**Comment by tamerbio** [comment]
many many thanks ,, would be also amazing to integrate `genrich` peak caller  a long with.

thanks once more

**Comment by dpryan79** [comment]
I've added Genrich as a peak caller for both ChIP-seq and ATAC-seq in my current branch. It seems to work quite well in my tests and also from what I've heard from others provided you have sufficient depth. In ChIP-seq it's not using replicates for peak calling whereas for ATAC-seq it is (simply due to there typically being many different IPs in ChIP experiments).

**Comment by katsikora** [comment]
This is now available in the latest release.
