### ISSUE TITLE
SLURM options

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#554]
Hi all,
I am a bit confused about the slurm options, so I need a bit of help if possible.
in the cluster.yaml file the following line exists:
`snakemake_cluster_cmd: module load slurm; SlurmEasy --mem-per-cpu {cluster.memory} --threads {threads} --log {snakePipes_cluster_logDir} --name {rule}.snakemake`
I assume that we need to change this to our specific settings that in the end will look like the one that follows a bit later:

in the tutorial this has changed to:
```
snakemake_cluster_cmd: module load slurm; sbatch --ntasks-per-node=1
   -c {threads} -J {rule}.snakemake --mem-per-cpu={cluster.memory}
   -p MYQUEUE -o {snakePipes_cluster_logDir}/{rule}.%j.out
   -e {snakePipes_cluster_logDir}/{rule}.%j.err
snakePipes_cluster_logDir: cluster_logs
```
**A.** I assume that this the way that mycluster.yaml should look like.

**B.** I do not understand the SlurmEasy part. Is this a separate module that is not part of the base SLURM

**C.** and also the options in **{}** as -c {threads}. Will those be assigned by each process? for example the bwa alligner process will ask as many as have been defined in the snakePipe chunk?

**D.** what about other entries that are variable, like --time, --mem
**E.** I assume that I also need to add to the above command options such as:
--account=, --mail-type=,--mail-user=
that are defined by the IT department.

Sorry for the long questions.

Best
Theo

**Comment by dpryan79** [comment]
A. Yes, something like that should work on most slurm clusters. That's not something we could ever give a generic command for, it will always have to be tailored to your cluster.

B. That's not a useful command for you, ignore it. See (A) above.

C. Yes, this will end up matching the number of threads given to each tool.

D. `--mem` is taken from the cluster.yaml for each workflow, `--time` is unused, since it's unknowable.

E. Yes, you will need to specify that if you want it, though I strongly encourage you to not specify that you want an email at that level since you'll get one for every single job. Instead see https://snakepipes.readthedocs.io/en/latest/content/advanced_usage.html#receiving-emails-upon-pipeline-completion
