### ISSUE TITLE
Request: ATAC-seq pipeline for single-end sequencing

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#563]
Hi snakePipes, thank you for the great pipelines. I would like to ask if it is possible to add 'single strand' option to the ATAC-seq pipeline?

Inspiration: 
https://github.com/taoliu/MACS/issues/145 
https://github.com/taoliu/MACS/issues/195 

Thank you!

**Comment by dpryan79** [comment]
Peak calling alone won’t produce reliable results. Determining fragment sizes is an important step since that determines what is likely to be histone and what is open chromatin. Since this information is lost with SE data we think it’s best to simply not do such analyses. In short, I think SE ATAC data is a waste of time to analyze.

**Comment by katsikora** [comment]
Hi Adrija,

we indeed do not support single end sequencing reads in our ATACseq pipeline and we have no plans to change that.

We could provide a second mode for calling ATACseq peaks with MACS2, like we do for the ChIPseq workflow (-f BAM instead of -f BAMPE), but we would still require paired end reads to have a good estimate of fragment size.

**Comment by AdrijaK** [comment]
Thank you for the insight. Would you consider that it is impossible to call nucleosome free regions using SE ATACseq libraries?

**Comment by katsikora** [comment]
I don't think you can distinguish nucleosome (long fragments) from nucleosome-free (short fragments) signal in SE ATACseq, as you don't have the fragment size information. As Devon pointed out before.

**Comment by AdrijaK** [comment]
Thanks. Although you cannot distinguish between nucleosome-free regions and nucleosome regions using SE ATACseq, can you still identify "open chromatin" regions?

**Comment by dpryan79** [comment]
Yes, but then you can't do peak calling and might as well just sequence whole genome DNA, since that will also bias toward open chromatin. SE ATAC-seq is a waste of money and resources.
