### ISSUE TITLE
resume and changing parameters [QUESTION][FEATURE]

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#582]
Hi again,

I am using the WGBS with metilene for Dif. methylated sites. 

After the pipeline has successfully finished  and I want to change the package to call the differentiated sites or do subbtles changes to the script, is there a way to resume the pipeline, so that it will use the intermediate files from all previous steps (I've opted to keep all temp files).

Best

**Comment by vivekbhr** [comment]
Hi. Yes, that's possible. If you move/rename the output folder for the corresponding step (such as the folder containing the methylation calls) and re-run the pipeline, the pipeline will begin from that step. So you can change parameters and re-run the workflow again.

**Comment by sunta3iouxos** [comment]
Thank you for the quick answer,
let's say that I want to cancel the pipeline (to free up resourcess for more important analysis) how can I do that and will the pipeline resume?
Best

**Comment by dpryan79** [comment]
If you kill snakePipes and then any jobs from it running on the cluster then just rerunning it will resume it with the new parameters. Please note that if the parameters will affect a step that has already been completed that you will need to delete the output from it manually, since otherwise the pipeline will think that that step can be skipped.

**Comment by sunta3iouxos** [comment]
Perfect
Thank you
