### ISSUE TITLE
using the wrapper to generate config file

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#626]
It seems that the command line which mentioned at the end of the default.yaml is not working anymore and needs to be updated. The reason is that snakepipes is called in the Snakefile and it is recognised as a non-existing module. `No module named 'snakePipes'`

**Comment by katsikora** [comment]
Leily, can you post exactly the code you used? Also checking module list from your terminal.

**Comment by LeilyR** [comment]
$ module load snakePipes
$ module load snakemake
$ snakemake --snakefile /package/anaconda3/envs/snakePipes-2.1.0/lib/python3.7/site-packages/snakePipes/workflows/DNA-mapping/Snakefile --configfile /package/anaconda3/envs/snakePipes-2.1.0/lib/python3.7/site-packages/snakePipes/workflows/DNA-mapping/defaults.yaml --directory /data/processing/linux_course_2020/output/leily2/ --cores 32
ModuleNotFoundError in line 2 of /package/anaconda3/envs/snakePipes-2.1.0/lib/python3.7/site-packages/snakePipes/workflows/DNA-mapping/Snakefile:
No module named 'snakePipes'
  File "/package/anaconda3/envs/snakePipes-2.1.0/lib/python3.7/site-packages/snakePipes/workflows/DNA-mapping/Snakefile", line 2, in <module>

**Comment by LeilyR** [comment]
I doesn't matter if you module snake pipes or not it cannot handle import snakpipes inside the Snakefile which makes sense to me

**Comment by katsikora** [comment]
Thanks for making your issue clear.

The following works for me:
########################################################################
sikora@maximus:~$ module list
Currently Loaded Modulefiles:
  1) snakemake/5.11     2) snakePipes/2.1.0

snakemake --snakefile /package/anaconda3/envs/snakePipes-2.1.0/lib/python3.7/site-packages/snakePipes/workflows/DNA-mapping/Snakefile --configfile /data/processing/sikora/snakepipes_ChIPseq_test/analysis/DNA-mapping.config.yaml --directory /data/processing/sikora/snakemake_cmd_test --cores 32

---- This analysis has been done using snakePipes version 2.1.0 ----
Building DAG of jobs...
###########################################################################3

As stated in read the docs, we currently recommend to start the analysis from a defaults.yaml that has been generated by a snakePipes run in your analysis output directory instead of the 'virgin' version. You can obtain this file by running a dryrun first.

**Comment by katsikora** [comment]
I'd suggest to remove these outdated command examples from defaults.yaml where still present, and to use the most up-to-date version from the documentation.

**Comment by katsikora** [comment]
There is another issue with 'filter_rules' being passed as input to bam_filtering, that comes up when I run the above command. This should be fixed -> I'll make a separate issue.
