### ISSUE TITLE
scRNAseq - setting --STARsoloCoords incorrectly parsed

### ISSUE THREAD

**Issue by powellhd** [maxplanck-ie/snakepipes#723]
Since my UMIs are 8-mers I tried to set the `STARsolo` `--STARsoloCoords` to `1,8,8,8` however the result from parsing is: `['1', ',', '8', ',', '8', ',', '8']` This results in it not being used.

**Comment by powellhd** [comment]
@dpryan79

**Comment by katsikora** [comment]
Hi there,

your coordinates don't make much sense in that you're specifying overlapping UMI and cell barcode positions.
Is '["1","8","9","8"]' what you want to specify? Please note that for the change in STARsoloCoords to take place, you have to specify '--myKit Custom' as well.

Best,

Katarzyna

**Comment by powellhd** [comment]
The command I used was:
`scRNAseq  --STARsoloCoords '1,8,8,8' --DAG --local --myKit CellSeq384 -i . -o ./output2 mm10`

If I use:
`scRNAseq  --STARsoloCoords '1,8,8,8' --myKit Custom --DAG --local -i . -o ./output2 mm10`

I get the following error:
---- This analysis has been done using snakePipes version 2.3.1 ----
TypeError in line 74 of /home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/workflows/scRNAseq/internals.snakefile:
stat: path should be string, bytes, os.PathLike or integer, not NoneType
  File "/home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/workflows/scRNAseq/Snakefile", line 21, in <module>
  File "/home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/workflows/scRNAseq/internals.snakefile", line 74, in <module>
  File "/home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/genericpath.py", line 30, in isfile
Error: snakemake returned an error code of 1, so processing is incomplete!

**Comment by LeilyR** [comment]
if you use custom, you need to provide a path to where your whitelist file is. (BCwhiteList in your config file)

**Comment by katsikora** [comment]
Hi Powellhd,

you're right that the STARsoloCoords was parsed incorrectly. This is now fixed in the latest snakePipes release 2.4.0.

Your coordinates are still incorrect, as you're specifying overlapping UMI and CB positions.
Here some suggestions for what might work for you:

If your barcode whitelist is still identical to the CelSeq2 whitelist (384 barcodes, 7nt long), then you can download it from our github repo at https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/workflows/scRNAseq/celseq_barcodes.384.1col.txt .

Then your command should read something like:

<code>scRNAseq --STARsoloCoords '1,8,9,7' --myKit Custom --BCwhiteList $PATH_TO_WHERE_YOU_PLACED_OUR_WHITELIST --DAG --local -i . -o ./output2 mm10 </code>

If your cell barcode whitelist is different than ours : 

<code>scRNAseq --STARsoloCoords '1,8,9,$LENGTH_OF_YOUR_CELL_BARCODE_IN_NUCLEOTIDES' --myKit Custom --BCwhiteList $PATH_TO_YOUR_OWN_WHITELIST --DAG --local -i . -o ./output2 mm10 </code>

Best,

Katarzyna
