### ISSUE TITLE
DNA-mapping error 

### ISSUE THREAD

**Issue by Dnarnas** [maxplanck-ie/snakepipes#775]
I installed latest snakePipes version 2.5.1 on MacOS 11.4 and tried to run the samples provided by the team. I got next error message:

/Users/work/miniconda3/envs/snakePipes/bin/DNA-mapping -i /Volumes/HD2/ChIP/ChIPseq -o /Volumes/HD2/ChIP --mapq 5 --local -j 10 --dedup hg38

TMPDIR=/Users/work/data PYTHONNOUSERSITE=True /Users/work/miniconda3/envs/snakePipes/bin/snakemake --use-conda --conda-prefix /Users/work/miniconda3/envs --latency-wait 300 --snakefile /Users/work/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/workflows/DNA-mapping/Snakefile --jobs 10 --directory /Volumes/HD/ChIP --configfile /Volumes/HD/ChIP/DNA-mapping.config.yaml --keep-going

---- This analysis has been done using snakePipes version 2.5.1 ----
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 10
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	5	Bowtie2
	1	all
	5	bamCoverage
	5	bamCoverage_filtered
	1	bamPE_fragment_size
	5	estimate_read_filtering
	5	filter_reads
	1	multiBamSummary
	1	multiQC
	1	plotCorrelation_pearson
	1	plotCorrelation_spearman
	1	plotCoverage
	1	plotPCA
	5	sambamba_flagstat
	5	sambamba_markdup
	5	samtools_filter
	5	samtools_index
	5	samtools_index_filtered
	58

[Wed Jun  2 10:56:43 2021]
rule Bowtie2:
    input: FASTQ/SRR6761499_R1.fastq.gz, FASTQ/SRR6761499_R2.fastq.gz
    output: Bowtie2/SRR6761499.Bowtie2_summary.txt, Bowtie2/SRR6761499.sorted.bam
    log: Bowtie2/logs/SRR6761499.sort.log
    jobid: 40
    benchmark: Bowtie2/.benchmark/Bowtie2.SRR6761499.benchmark
    wildcards: sample=SRR6761499
    threads: 10

Activating conda environment: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
[main_samview] fail to read the header from "-".
[Wed Jun  2 10:56:45 2021]
Error in rule Bowtie2:
    jobid: 40
    output: Bowtie2/SRR6761499.Bowtie2_summary.txt, Bowtie2/SRR6761499.sorted.bam
    log: Bowtie2/logs/SRR6761499.sort.log (check log file(s) for error message)
    conda-env: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
    shell:
        
            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761499_R1.fastq.gz -2 FASTQ/SRR6761499_R2.fastq.gz               --fr             --rg-id SRR6761499             --rg DS:SRR6761499 --rg PL:ILLUMINA --rg SM:SRR6761499             -p 10             2> Bowtie2/SRR6761499.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761499 -@ 2 -O bam - > Bowtie2/SRR6761499.sorted.bam 2> Bowtie2/logs/SRR6761499.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job Bowtie2 since they might be corrupted:
Bowtie2/SRR6761499.Bowtie2_summary.txt, Bowtie2/SRR6761499.sorted.bam
Job failed, going on with independent jobs.

When I checked the Bowtie2 log file I saw next line:
samtools sort: failed to read header from "-"

Could you please pointed out what I'm doing wrong?
Thanks

**Comment by LeilyR** [comment]
are the bam files empty?

**Comment by vitaly001** [comment]
Hi, 
I think that bam files are empty, since it falls to read from header.
Thanks

**Comment by vitaly001** [comment]
I run it with —verbose option to see if it will provide more information:

/Users/work/miniconda3/envs/snakePipes/bin/DNA-mapping -i /Volumes/HD2/ChIP/ChIPseq -o /Volumes/HD2/ChIP --mapq 5 --local -j 10 --dedup --verbose hg38

TMPDIR=/Users/work/data PYTHONNOUSERSITE=True /Users/work/miniconda3/envs/snakePipes/bin/snakemake --use-conda --conda-prefix /Users/work/miniconda3/envs --latency-wait 300 --snakefile /Users/work/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/workflows/DNA-mapping/Snakefile --jobs 10 --directory /Volumes/HD2/ChIP --configfile /Volumes/HD2/ChIP/DNA-mapping.config.yaml --keep-going --printshellcmds


---- This analysis has been done using snakePipes version 2.5.1 ----
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 10
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	5	Bowtie2
	1	all
	5	bamCoverage
	5	bamCoverage_filtered
	1	bamPE_fragment_size
	5	estimate_read_filtering
	5	filter_reads
	1	multiBamSummary
	1	multiQC
	1	plotCorrelation_pearson
	1	plotCorrelation_spearman
	1	plotCoverage
	1	plotPCA
	5	sambamba_flagstat
	5	sambamba_markdup
	5	samtools_filter
	5	samtools_index
	5	samtools_index_filtered
	58

[Tue Jun  8 10:08:52 2021]
rule Bowtie2:
    input: FASTQ/SRR6761499_R1.fastq.gz, FASTQ/SRR6761499_R2.fastq.gz
    output: Bowtie2/SRR6761499.Bowtie2_summary.txt, Bowtie2/SRR6761499.sorted.bam
    log: Bowtie2/logs/SRR6761499.sort.log
    jobid: 40
    benchmark: Bowtie2/.benchmark/Bowtie2.SRR6761499.benchmark
    wildcards: sample=SRR6761499
    threads: 10


            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761499_R1.fastq.gz -2 FASTQ/SRR6761499_R2.fastq.gz               --fr             --rg-id SRR6761499             --rg DS:SRR6761499 --rg PL:ILLUMINA --rg SM:SRR6761499             -p 10             2> Bowtie2/SRR6761499.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761499 -@ 2 -O bam - > Bowtie2/SRR6761499.sorted.bam 2> Bowtie2/logs/SRR6761499.sort.log;
            rm -rf $MYTEMP
            
Activating conda environment: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
[main_samview] fail to read the header from "-".
[Tue Jun  8 10:08:54 2021]
Error in rule Bowtie2:
    jobid: 40
    output: Bowtie2/SRR6761499.Bowtie2_summary.txt, Bowtie2/SRR6761499.sorted.bam
    log: Bowtie2/logs/SRR6761499.sort.log (check log file(s) for error message)
    conda-env: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
    shell:
        
            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761499_R1.fastq.gz -2 FASTQ/SRR6761499_R2.fastq.gz               --fr             --rg-id SRR6761499             --rg DS:SRR6761499 --rg PL:ILLUMINA --rg SM:SRR6761499             -p 10             2> Bowtie2/SRR6761499.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761499 -@ 2 -O bam - > Bowtie2/SRR6761499.sorted.bam 2> Bowtie2/logs/SRR6761499.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job Bowtie2 since they might be corrupted:
Bowtie2/SRR6761499.Bowtie2_summary.txt, Bowtie2/SRR6761499.sorted.bam
Job failed, going on with independent jobs.

[Tue Jun  8 10:08:54 2021]
rule Bowtie2:
    input: FASTQ/SRR6761497_R1.fastq.gz, FASTQ/SRR6761497_R2.fastq.gz
    output: Bowtie2/SRR6761497.Bowtie2_summary.txt, Bowtie2/SRR6761497.sorted.bam
    log: Bowtie2/logs/SRR6761497.sort.log
    jobid: 38
    benchmark: Bowtie2/.benchmark/Bowtie2.SRR6761497.benchmark
    wildcards: sample=SRR6761497
    threads: 10


            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761497_R1.fastq.gz -2 FASTQ/SRR6761497_R2.fastq.gz               --fr             --rg-id SRR6761497             --rg DS:SRR6761497 --rg PL:ILLUMINA --rg SM:SRR6761497             -p 10             2> Bowtie2/SRR6761497.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761497 -@ 2 -O bam - > Bowtie2/SRR6761497.sorted.bam 2> Bowtie2/logs/SRR6761497.sort.log;
            rm -rf $MYTEMP
            
Activating conda environment: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
[main_samview] fail to read the header from "-".
[Tue Jun  8 10:08:55 2021]
Error in rule Bowtie2:
    jobid: 38
    output: Bowtie2/SRR6761497.Bowtie2_summary.txt, Bowtie2/SRR6761497.sorted.bam
    log: Bowtie2/logs/SRR6761497.sort.log (check log file(s) for error message)
    conda-env: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
    shell:
        
            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761497_R1.fastq.gz -2 FASTQ/SRR6761497_R2.fastq.gz               --fr             --rg-id SRR6761497             --rg DS:SRR6761497 --rg PL:ILLUMINA --rg SM:SRR6761497             -p 10             2> Bowtie2/SRR6761497.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761497 -@ 2 -O bam - > Bowtie2/SRR6761497.sorted.bam 2> Bowtie2/logs/SRR6761497.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job Bowtie2 since they might be corrupted:
Bowtie2/SRR6761497.Bowtie2_summary.txt, Bowtie2/SRR6761497.sorted.bam
Job failed, going on with independent jobs.

[Tue Jun  8 10:08:55 2021]
rule Bowtie2:
    input: FASTQ/SRR6761502_R1.fastq.gz, FASTQ/SRR6761502_R2.fastq.gz
    output: Bowtie2/SRR6761502.Bowtie2_summary.txt, Bowtie2/SRR6761502.sorted.bam
    log: Bowtie2/logs/SRR6761502.sort.log
    jobid: 41
    benchmark: Bowtie2/.benchmark/Bowtie2.SRR6761502.benchmark
    wildcards: sample=SRR6761502
    threads: 10


            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761502_R1.fastq.gz -2 FASTQ/SRR6761502_R2.fastq.gz               --fr             --rg-id SRR6761502             --rg DS:SRR6761502 --rg PL:ILLUMINA --rg SM:SRR6761502             -p 10             2> Bowtie2/SRR6761502.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761502 -@ 2 -O bam - > Bowtie2/SRR6761502.sorted.bam 2> Bowtie2/logs/SRR6761502.sort.log;
            rm -rf $MYTEMP
            
Activating conda environment: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
[main_samview] fail to read the header from "-".
[Tue Jun  8 10:08:57 2021]
Error in rule Bowtie2:
    jobid: 41
    output: Bowtie2/SRR6761502.Bowtie2_summary.txt, Bowtie2/SRR6761502.sorted.bam
    log: Bowtie2/logs/SRR6761502.sort.log (check log file(s) for error message)
    conda-env: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
    shell:
        
            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761502_R1.fastq.gz -2 FASTQ/SRR6761502_R2.fastq.gz               --fr             --rg-id SRR6761502             --rg DS:SRR6761502 --rg PL:ILLUMINA --rg SM:SRR6761502             -p 10             2> Bowtie2/SRR6761502.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761502 -@ 2 -O bam - > Bowtie2/SRR6761502.sorted.bam 2> Bowtie2/logs/SRR6761502.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job Bowtie2 since they might be corrupted:
Bowtie2/SRR6761502.Bowtie2_summary.txt, Bowtie2/SRR6761502.sorted.bam
Job failed, going on with independent jobs.

[Tue Jun  8 10:08:57 2021]
rule Bowtie2:
    input: FASTQ/SRR6761498_R1.fastq.gz, FASTQ/SRR6761498_R2.fastq.gz
    output: Bowtie2/SRR6761498.Bowtie2_summary.txt, Bowtie2/SRR6761498.sorted.bam
    log: Bowtie2/logs/SRR6761498.sort.log
    jobid: 39
    benchmark: Bowtie2/.benchmark/Bowtie2.SRR6761498.benchmark
    wildcards: sample=SRR6761498
    threads: 10


            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761498_R1.fastq.gz -2 FASTQ/SRR6761498_R2.fastq.gz               --fr             --rg-id SRR6761498             --rg DS:SRR6761498 --rg PL:ILLUMINA --rg SM:SRR6761498             -p 10             2> Bowtie2/SRR6761498.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761498 -@ 2 -O bam - > Bowtie2/SRR6761498.sorted.bam 2> Bowtie2/logs/SRR6761498.sort.log;
            rm -rf $MYTEMP
            
Activating conda environment: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
[main_samview] fail to read the header from "-".
[Tue Jun  8 10:08:58 2021]
Error in rule Bowtie2:
    jobid: 39
    output: Bowtie2/SRR6761498.Bowtie2_summary.txt, Bowtie2/SRR6761498.sorted.bam
    log: Bowtie2/logs/SRR6761498.sort.log (check log file(s) for error message)
    conda-env: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
    shell:
        
            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761498_R1.fastq.gz -2 FASTQ/SRR6761498_R2.fastq.gz               --fr             --rg-id SRR6761498             --rg DS:SRR6761498 --rg PL:ILLUMINA --rg SM:SRR6761498             -p 10             2> Bowtie2/SRR6761498.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761498 -@ 2 -O bam - > Bowtie2/SRR6761498.sorted.bam 2> Bowtie2/logs/SRR6761498.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job Bowtie2 since they might be corrupted:
Bowtie2/SRR6761498.Bowtie2_summary.txt, Bowtie2/SRR6761498.sorted.bam
Job failed, going on with independent jobs.

[Tue Jun  8 10:08:58 2021]
rule Bowtie2:
    input: FASTQ/SRR6761495_R1.fastq.gz, FASTQ/SRR6761495_R2.fastq.gz
    output: Bowtie2/SRR6761495.Bowtie2_summary.txt, Bowtie2/SRR6761495.sorted.bam
    log: Bowtie2/logs/SRR6761495.sort.log
    jobid: 37
    benchmark: Bowtie2/.benchmark/Bowtie2.SRR6761495.benchmark
    wildcards: sample=SRR6761495
    threads: 10


            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761495_R1.fastq.gz -2 FASTQ/SRR6761495_R2.fastq.gz               --fr             --rg-id SRR6761495             --rg DS:SRR6761495 --rg PL:ILLUMINA --rg SM:SRR6761495             -p 10             2> Bowtie2/SRR6761495.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761495 -@ 2 -O bam - > Bowtie2/SRR6761495.sorted.bam 2> Bowtie2/logs/SRR6761495.sort.log;
            rm -rf $MYTEMP
            
Activating conda environment: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
[main_samview] fail to read the header from "-".
[Tue Jun  8 10:09:00 2021]
Error in rule Bowtie2:
    jobid: 37
    output: Bowtie2/SRR6761495.Bowtie2_summary.txt, Bowtie2/SRR6761495.sorted.bam
    log: Bowtie2/logs/SRR6761495.sort.log (check log file(s) for error message)
    conda-env: /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed
    shell:
        
            TMPDIR=/Users/work/data
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761495_R1.fastq.gz -2 FASTQ/SRR6761495_R2.fastq.gz               --fr             --rg-id SRR6761495             --rg DS:SRR6761495 --rg PL:ILLUMINA --rg SM:SRR6761495             -p 10             2> Bowtie2/SRR6761495.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/SRR6761495 -@ 2 -O bam - > Bowtie2/SRR6761495.sorted.bam 2> Bowtie2/logs/SRR6761495.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job Bowtie2 since they might be corrupted:
Bowtie2/SRR6761495.Bowtie2_summary.txt, Bowtie2/SRR6761495.sorted.bam
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /Volumes/HD2/ChIP/.snakemake/log/2021-06-08T100851.875693.snakemake.log

--- Config ---------------------------------------------------------------------
config file: /Volumes/HD2/ChIP/DNA-mapping.config.yaml
GCBias: False
NMaskedIndex: 
SNPfile: 
UMIBarcode: False
UMIDedup: False
UMIDedupOpts: None
UMIDedupSep: _
VCFfile: 
aligner: Bowtie2
alignerOpts: None
allele_mode: None
baseDir: /Users/work/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes
bcPattern: NNNNCCCCCCCC
bwBinSize: 25
clusterConfig: shared/cluster.yaml
clusterConfigFile: None
configFile: None
configMode: manual
createDAG: False
cutntag: False
dedup: True
downsample: None
emailAddress: None
emailSender: None
ext: .fastq.gz
fastqc: False
fragmentLength: 200
genome: hg38
indir: /Volumes/HD2/ChIP/ChIPseq
insertSizeMax: 1000
keepTemp: False
local: True
mapq: 5
mateOrientation: --fr
maxJobs: 10
max_thread: 25
mode: mapping
oldConfig: None
onlySSL: False
organismsDir: shared/organisms
outdir: /Volumes/HD2/ChIP
pipeline: dna-mapping
plotFormat: png
properPairs: False
qualimap: False
reads: ['_R1', '_R2']
smtpPassword: None
smtpPort: 0
smtpServer: None
smtpUsername: None
snakemakeOptions:  --use-conda --conda-prefix /Users/work/miniconda3/envs 
strains: 
tempDir: /Users/work/data
toolsVersion: True
trim: False
trimmer: cutadapt
trimmerOptions: None
verbose: True
workingdir: /Volumes/HD2/ChIP
-------------------------------------------------------------------------------- 


--- Genome ---------------------------------------------------------------------
config file: /Users/work/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/organisms/hg38.yaml
blacklist_bed: HD2/data/repository/organisms/GRCh38_ensembl/akundaje/blacklist.UseMe.bed
bowtie2_index: HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome
bwa_index: HD2/data/repository/organisms/GRCh38_ensembl/BWAindex/genome.fa
extended_coding_regions_gtf: HD2/data/repository/organisms/GRCh38_ensembl/gencode/release_27/genes.slop.gtf
genes_bed: HD2/data/repository/organisms/GRCh38_ensembl/gencode/release_27/genes.bed
genes_gtf: HD2/data/repository/organisms/GRCh38_ensembl/gencode/release_27/genes.gtf
genome_2bit: HD2/data/repository/organisms/GRCh38_ensembl/genome_fasta/genome.2bit
genome_fasta: HD2/data/repository/organisms/GRCh38_ensembl/genome_fasta/genome.fa
genome_index: HD2/data/repository/organisms/GRCh38_ensembl/genome_fasta/genome.fa.fai
genome_size: 2900338458
hisat2_index: HD2/data/repository/organisms/GRCh38_ensembl/HISAT2Index/genome
ignoreForNormalization: KI270728.1 KI270727.1 KI270442.1 KI270729.1 GL000225.1 KI270743.1 GL000008.2 GL000009.2 KI270747.1 KI270722.1 GL000194.1 KI270742.1 GL000205.2 GL000195.1 KI270736.1 KI270733.1 GL000224.1 GL000219.1 KI270719.1 GL000216.2 KI270712.1 KI270706.1 KI270725.1 KI270744.1 KI270734.1 GL000213.1 GL000220.1 KI270715.1 GL000218.1 KI270749.1 KI270741.1 GL000221.1 KI270716.1 KI270731.1 KI270751.1 KI270750.1 KI270519.1 GL000214.1 KI270708.1 KI270730.1 KI270438.1 KI270737.1 KI270721.1 KI270738.1 KI270748.1 KI270435.1 GL000208.1 KI270538.1 KI270756.1 KI270739.1 KI270757.1 KI270709.1 KI270746.1 KI270753.1 KI270589.1 KI270726.1 KI270735.1 KI270711.1 KI270745.1 KI270714.1 KI270732.1 KI270713.1 KI270754.1 KI270710.1 KI270717.1 KI270724.1 KI270720.1 KI270723.1 KI270718.1 KI270317.1 KI270740.1 KI270755.1 KI270707.1 KI270579.1 KI270752.1 KI270512.1 KI270322.1 GL000226.1 KI270311.1 KI270366.1 KI270511.1 KI270448.1 KI270521.1 KI270581.1 KI270582.1 KI270515.1 KI270588.1 KI270591.1 KI270522.1 KI270507.1 KI270590.1 KI270584.1 KI270320.1 KI270382.1 KI270468.1 KI270467.1 KI270362.1 KI270517.1 KI270593.1 KI270528.1 KI270587.1 KI270364.1 KI270371.1 KI270333.1 KI270374.1 KI270411.1 KI270414.1 KI270510.1 KI270390.1 KI270375.1 KI270420.1 KI270509.1 KI270315.1 KI270302.1 KI270518.1 KI270530.1 KI270304.1 KI270418.1 KI270424.1 KI270417.1 KI270508.1 KI270303.1 KI270381.1 KI270529.1 KI270425.1 KI270396.1 KI270363.1 KI270386.1 KI270465.1 KI270383.1 KI270384.1 KI270330.1 KI270372.1 KI270548.1 KI270580.1 KI270387.1 KI270391.1 KI270305.1 KI270373.1 KI270422.1 KI270316.1 KI270338.1 KI270340.1 KI270583.1 KI270334.1 KI270429.1 KI270393.1 KI270516.1 KI270389.1 KI270466.1 KI270388.1 KI270544.1 KI270310.1 KI270412.1 KI270395.1 KI270376.1 KI270337.1 KI270335.1 KI270378.1 KI270379.1 KI270329.1 KI270419.1 KI270336.1 KI270312.1 KI270539.1 KI270385.1 KI270423.1 KI270392.1 KI270394.1 X Y MT
known_splicesites: HD2/data/repository/organisms/GRCh38_ensembl/gencode/release_27/HISAT2/splice_sites.txt
rmsk_file: HD2/data/repository/organisms/GRCh38_ensembl/UCSC/hg38/rmsk.txt
star_index: HD2/data/repository/organisms/GRCh38_ensembl/STARIndex/2.7.4a/
-------------------------------------------------------------------------------- 

--- Workflow parameters --------------------------------------------------------
samples: ['SRR6761495', 'SRR6761497', 'SRR6761498', 'SRR6761499', 'SRR6761502']
paired: True
read extension: ['_R1', '_R2']
fastq dir: FASTQ
maximum insert size (Bowtie2 -X): 1000
-------------------------------------------------------------------------------- 

--- Environment ----------------------------------------------------------------
$TMPDIR:  /Users/work/data
$HOSTNAME:  
-------------------------------------------------------------------------------- 


 !!! ERROR in DNA mapping workflow! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Dnarnas** [comment]
I think I found the source of mistake. Run the bowtie2 only and it show that the problem was in indexes. I will download the premade indexes and run it again.

**Comment by Dnarnas** [comment]
I tried to go find the error and run the bowtie2 alone in snikePipe environment. I cd to the output folder and run bowtie 2 on selected files. 
conda/source activate /Users/work/miniconda3/envs/18d19f6292ab9b7cced85d8d7410f4ed

(18d19f6292ab9b7cced85d8d7410f4ed) /Volumes/HD2/ChIP $ bowtie2 -X 1000 -x HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome -1 FASTQ/SRR6761495_R1.fastq.gz -2 FASTQ/SRR6761495_R2.fastq.gz --fr--rg-id SRR6761495 --rg DS:SRR6761495 --rg PL:ILLUMINA --rg SM:SRR6761495-p 20 > test.sam 2> Bowtie2/Bowtie2_summary.txt

Log file indicated next:
(ERR): "HD2/data/repository/organisms/GRCh38_ensembl/BowtieIndex/genome" does not exist or is not a Bowtie 2 index
Exiting now ...

I downloaded again the premade indexes from https://zenodo.org/record/4471116#.YMI1mxOYVqt
 and run again after modifiyng organizm yaml file.
Below is my yaml file:
blacklist_bed: ''
bowtie2_index: HD2/data/repository/GRCh38_gencode_release29/BowtieIndex/genome
bwa_index: HD2/data/repository/GRCh38_gencode_release29/BWAIndex/genome.fa
bwameth_index: HD2/data/repository/GRCh38_gencode_release29/BWAmethIndex/genome.fa
extended_coding_regions_gtf: HD2/data/repository/GRCh38_gencode_release29/annotation/genes.slop.gtf
genes_bed: HD2/data/repository/GRCh38_gencode_release29/annotation/genes.bed
genes_gtf: HD2/data/repository/GRCh38_gencode_release29/annotation/genes.gtf
genome_2bit: HD2/data/repository/GRCh38_gencode_release29/genome_fasta/genome.2bit
genome_dict: HD2/data/repository/GRCh38_gencode_release29/genome_fasta/genome.dict
genome_fasta: HD2/data/repository/GRCh38_gencode_release29/genome_fasta/genome.fa
genome_index: HD2/data/repository/GRCh38_gencode_release29/genome_fasta/genome.fa.fai
genome_size: 2900338458
hisat2_index: HD2/data/repository/GRCh38_gencode_release29/HISAT2Index/genome
ignoreForNormalization: " ''
spikein_blacklist_bed: ''
spikein_genes_gtf: ''
star_index: HD2/data/repository/GRCh38_gencode_release29/STARIndex/

Here I only deleted the line ignoreForNormalization since it is too big. 

I double check the path to index and it is correct /Volumes/HD2/data/repository/GRCh38_gencode_release29/BowtieIndex

Since both path to the index and index itself are correct I do not really understand why I see the error.
Below is DNA-mapping.config.yaml:
GCBias: false
NMaskedIndex: ''
SNPfile: ''
UMIBarcode: false
UMIDedup: false
UMIDedupOpts: null
UMIDedupSep: _
VCFfile: ''
aligner: Bowtie2
alignerOpts: null
allele_mode: null
baseDir: /Users/work/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes
bcPattern: NNNNCCCCCCCC
bwBinSize: 25
clusterConfig: shared/cluster.yaml
clusterConfigFile: null
configFile: null
configMode: manual
createDAG: false
cutntag: false
dedup: true
downsample: null
emailAddress: null
emailSender: null
ext: .fastq.gz
fastqc: false
fragmentLength: 200
genome: hg38
indir: /Volumes/HD2/ChIP/ChIPseq
insertSizeMax: 1000
keepTemp: false
local: true
mapq: 5
mateOrientation: --fr
maxJobs: 10
max_thread: 25
mode: mapping
oldConfig: null
onlySSL: false
organismsDir: shared/organisms
outdir: /Volumes/HD2/ChIP
pipeline: dna-mapping
plotFormat: png
properPairs: false
qualimap: false
reads:
- _R1
- _R2
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /Users/work/miniconda3/envs '
strains: ''
tempDir: /Users/work/data
toolsVersion: true
trim: false
trimmer: cutadapt
trimmerOptions: null
verbose: true
workingdir: /Volumes/HD2/ChIP

**Comment by LeilyR** [comment]
I have downloaded and ran the same command line and could not produce this error. Does `HD2/data/repository/GRCh38_gencode_release29/BowtieIndex/genome` actually exists?

**Comment by Dnarnas** [comment]
Thank you LeilyR, incorrect path to the index was the problem
