### ISSUE TITLE
DESeq2 report fails on a large number of samples

### ISSUE THREAD

**Issue by HudoGriz** [maxplanck-ie/snakepipes#816]
Hello!

With a large sample size (I had 60) the PCA manual scaling:

https://github.com/maxplanck-ie/snakepipes/blob/c5f47d93ecc3cc120aff55a10e4a6ab441a5b9d8/snakePipes/shared/rscripts/DESeq2Report.Rmd#L229

produces the following error:
`Insufficient values in manual scale. 60 needed but only 36 provided.`

I am using the 2.5.3 version.

Thanks for providing this amazing tool,

Blaž V.

**Comment by katsikora** [comment]
Hi Blaz,

thanks for reporting! We know about this issue - what actually fails is only the PCA plot, not the DESeq2 workflow itself.
This is because there is a 1:1 mapping between sample names and plotting shape hardcoded, with 'only' 36 shapes provided. We're going to remove this mapping in the future, or retain for a small number of samples.

If you'd like a fast solution for yourself, you could use the Rmd file underlying the DESeq2 report to rerun your analysis, and just modify (or remove) that unfortunate line from the Rmd.

Would that do for you for now?

Best,

Katarzyna

**Comment by HudoGriz** [comment]
Glad to hear that the issue will be addressed.

Yes, for now I commented out the PCA plot and substituted it with the one created by deepTools.

Thank you for the swift reply,

Blaž
