### ISSUE TITLE
[Question] bam Coverage bw files clarification 

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#948]
Hi Katarzyna,
regarding the DNA-mapping and ChIP-seq pipelines there are few bw files created and I would like to know which ones are to be used for visualisation or other purposes (plots etc), so that comparisons can be done among samples.
the files I see for my analysis that also include a spike in are:
```
A006850324_209957_S1_L000.filtered.seq_depth_norm.bw
A006850324_209957_S1_L000.host_scaled.BYhost.bw
A006850324_209957_S1_L000.host_scaled.BYspikein.bw
A006850324_209957_S1_L000.seq_depth_norm.bw
```
which ones are to be used if there is no spike-in organism and which with.

Is it also possible to add this information to the [snakepipes info](https://snakepipes.readthedocs.io)

**Comment by katsikora** [comment]
Hi,

if you wish to use spikein for normalization, then "A006850324_209957_S1_L000.host_scaled.BYspikein.bw" would be the way to go. Otherwise, "A006850324_209957_S1_L000.filtered.seq_depth_norm.bw", assuming there was filtering applied on the bam file level.

Sure, we can make the docs a bit more explicit .

Best,

Katarzyna

**Comment by sunta3iouxos** [comment]
Many many thanks.
